import { RedirectToSignIn, SignInButton, SignOutButton, SignedIn, SignedOut, UserProfile, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { isLoaded, isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignedIn>
          <h1 className="text-2xl border-b-2 border-dashed ">Hello, {user?.firstName}!</h1>
          <div className="py-2 px-6 mt-4 rounded-lg bg-orange-600">
            <SignOutButton />
          </div>
        </SignedIn>
        <SignedOut>
          <h1 className="text-2xl border-b-2 border-dashed ">Hello!</h1>
          <div className="py-2 px-6 mt-4 rounded-lg bg-orange-600">
            <SignInButton />
          </div>
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
